version: "3.9"
services:
  web_api:
    build: .
    container_name: classroom_api
    ports:
      - "8080:80"
      
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=YukiElectric@123